name: build-preview
run-name: build pull request preview

on:
  workflow_call:
  workflow_dispatch:

env:
  PREVIEWS_FOLDER: preview

permissions:
  contents: write
  pull-requests: write

jobs:
  build-preview:
    runs-on: ubuntu-latest

    steps:
      # for debugging
      - uses: crazy-max/ghaction-dump-context@v2

      - name: Checkout branch contents
        uses: actions/checkout@v4
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.head_ref }}

      - name: Install Ruby using rbenv
        run: |
          sudo apt update
          sudo apt install -y rbenv
          rbenv install 3.1.4
          rbenv global 3.1.4
          echo 'export PATH="$HOME/.rbenv/bin:$PATH"' >> ~/.bashrc
          echo 'eval "$(rbenv init -)"' >> ~/.bashrc
          source ~/.bashrc
          ruby -v  # Verify Ruby installation

      - name: Install Bundler and Dependencies
        run: |
          gem install bundler
          bundle install

      - name: Get Pages URL
        if: github.event.action != 'closed'
        id: pages
        uses: actions/configure-pages@v4

      # for debugging
      - if: runner.debug == '1'
        uses: mxschmitt/action-tmate@v3

      - name: Build preview version of site
        if: github.event.action != 'closed'
        run: |
          JEKYLL_ENV=production bundle exec jekyll build --baseurl "${{ steps.pages.outputs.base_path || '' }}/${{ env.PREVIEWS_FOLDER }}/pr-${{ github.event.number }}"

      - name: Commit preview to Pages branch
        uses: rossjrw/pr-preview-action@v1.4.7
        with:
          source-dir: _site
          umbrella-dir: ${{ env.PREVIEWS_FOLDER }}
