name: build-site
run-name: build live site

on:
  workflow_call:
  workflow_dispatch:

# Variables
env:
  PREVIEWS_FOLDER: preview

permissions:
  contents: write

jobs:
  build-site:
    runs-on: ubuntu-latest

    steps:
      # Debugging
      - uses: crazy-max/ghaction-dump-context@v2

      - name: Checkout branch contents
        uses: actions/checkout@v4

      - name: Install Ruby using rbenv
        run: |
          sudo apt update
          sudo apt install -y rbenv
          rbenv install 3.1.4
          rbenv global 3.1.4
          echo 'export PATH="$HOME/.rbenv/bin:$PATH"' >> ~/.bashrc
          echo 'eval "$(rbenv init -)"' >> ~/.bashrc
          source ~/.bashrc
          ruby -v  # Verify Ruby installation

      - name: Install Bundler and Dependencies
        run: |
          gem install bundler
          bundle install

      - name: Get Pages URL
        id: pages
        uses: actions/configure-pages@v4

      # Debugging
      - if: runner.debug == '1'
        uses: mxschmitt/action-tmate@v3

      - name: Set root URL
        run: |
          printf "\n\nurl: ${{ steps.pages.outputs.origin }}" >> _config.yaml

      - name: Build live version of site
        run: |
          JEKYLL_ENV=production bundle exec jekyll build --baseurl "${{ steps.pages.outputs.base_path || '' }}"

      - name: Commit live site to Pages branch
        uses: JamesIves/github-pages-deploy-action@v4.5.0
        with:
          folder: _site
          clean-exclude: ${{ env.PREVIEWS_FOLDER }}
          force: false
